OUTPUT_PATH = 'output'
FOUND_DOCS = OUTPUT_PATH + '/' + 'pregnancy_files.txt'
PREPROCESSED_DOCS = OUTPUT_PATH + '/' + 'document_content.pickle'
VISUALIZATION = OUTPUT_PATH + '/' + 'view.html'
FINAL_REPORT = OUTPUT_PATH + '/' + 'final_report.json'
